version: "3.7"
services:
  ####################### SETUP OF DOCKER CONTAINERS #############################
  persuasion-deployment:
    container_name: persuasion-engine
    build:
      context: .
      dockerfile: persuasion.Dockerfile
    image: persuasion-engine:latest
    command:
      - python3
      - /usr/local/src/persuasion_engine/run.py
    expose:
      - "9092"
      - "6379"
    ports:
      - "5000:5000"